services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: bookshelf
      POSTGRES_PASSWORD: bookshelf
    ports:
      - '5432:5432'
  mailpit:
    image: axllent/mailpit:v1.20
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - '1025:1025'
      - '8025:8025'
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: ["start-dev", "--import-realm", "--http-port=8090"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8090:8090'
    volumes:
      - ./src/test/resources/keycloak/test-realm.json:/opt/keycloak/data/import/test-realm-realm.json:ro
